index:
    path:            /
    defaults: { _controller: 'App\Controller\FrontController::index' }

ajax_tricks:
    path:            /{page}
    defaults: { _controller: 'App\Controller\FrontController::ajaxTricks' }
    condition:       "request.isXmlHttpRequest()"
    requirements:
        page:        '\d+'

trick:
    path:            /trick-{id}
    defaults: { _controller: 'App\Controller\FrontController::trick' }
    requirements:
        id:          '\d+'

ajax_comments:
    path:            /trick-{id}/{page}
    defaults: { _controller: 'App\Controller\FrontController::ajaxComments' }
    condition:       "request.isXmlHttpRequest()"
    requirements:
        id:          '\d+'
        page:        '\d+'

edit_trick:
  path:              /trick-edit-{id}
  defaults: { _controller: 'App\Controller\BackController::editTrick' }
  requirements:
    id:              '\d+'

add_trick:
  path:              /trick-add
  defaults: { _controller: 'App\Controller\BackController::addTrick' }

delete_trick:
  path:              /trick-delete-{id}
  defaults: { _controller: 'App\Controller\BackController::deleteTrick' }
  requirements:
    id:              '\d+'

delete_video:
  path:              /video-delete-{id}
  defaults: { _controller: 'App\Controller\BackController::deleteVideo' }
  requirements:
    id:              '\d+'

delete_trick_photo:
  path:              /trick-photo-delete-{id}
  defaults: { _controller: 'App\Controller\BackController::deleteTrickPhoto' }
  requirements:
    id:              '\d+'

delete_front_photo:
  path:              /front-photo-delete-{id}
  defaults: { _controller: 'App\Controller\BackController::deleteFrontPhoto' }
  requirements:
    id:              '\d+'

login:
    path:            /login
    defaults:
        _controller: App\Controller\SecurityController::login

logout:
    path:            /logout

register:
  path:              /register
  defaults:
    _controller:     App\Controller\SecurityController::register
